### ISSUE TITLE
تغییر کلمه عبور میل سرور با mvc

### ISSUE THREAD

**Issue by alirezaseif28** [VahidN/MVC-Samples#1]
سلام جناب مهندس نصیری
ممنون میشم راهنمایی بفرمایید.
می خواستم به وسیله mvc
کلمه عبور میل سرورم در صورت تغییر مدیر تغییر بدم؟
تنظیمات مربوط به میل سرور در برنامه نگه داشتم.در صورتی که مدیر رمز تغییر داد اول رمز میل سرور تغییر بدهد در صورت موفقیت رمز در بانک اطلاعاتی تغییر کند.
مرسی

**Comment by VahidN** [comment]
سلام؛ براي اين نوع سؤالات از انجمن‌هاي عمومي استفاده كنيد؛ مانند
http://barnamenevis.org

**Comment by alirezaseif28** [comment]
مرسی
