### ISSUE TITLE
تغییر .netframework 4.5.2 به .netframework 4.6.1

### ISSUE THREAD

**Issue by alirezaseif28** [VahidN/MVC-Samples#3]
سلام 
ببخشید من یه سوال دارم . لطفا من را راهنمایی کنید.
یه پروژه 
mvc
دارم که چند سالی هست که مشغول گسترش دادن ان هستم . 
با تغییر 
.netframework 
از نسخه ی 4.5.2 به نسخه 4.6.1
به خطای 
Compilation Error
برمی خورم.
لطفا راهنمایی بفرمایید.
با تشکر

**Comment by VahidN** [comment]
<div dir="rtl">

لطفا از انجمن‌هاي عمومي مانند استك‌اورفلو براي طرح سؤالات عمومي به همراه ارائه‌ي خطاي كامل استفاده كنيد
